### ISSUE TITLE
Is there a way to get the widget contained by a BoxyChild?

### ISSUE THREAD

**Issue by metent** [PixelToast/flutter-boxy#11]
I'm trying to write a list-like custom layout where all the list items are ordered in the screen according to their properties. I have created a list of items `List<BoxyChild>` using the `inflate` method of `BoxyDelegate` and now I would like to sort this list and then `position` the items on the screen accordingly. But the class `InflatedChildHandle` (which is inherited by `BoxyChild`) has `_widget` as a private field. Is there any other way to get the widget contained by the `BoxyChild`?

**Comment by PixelToast** [comment]
Implemented in 2.0.5!

https://pub.dev/documentation/boxy/latest/inflating_element/InflatedChildHandle/context.html
