### ISSUE TITLE
Finding child Offeset

### ISSUE THREAD

**Issue by kobyhallx** [PixelToast/flutter-boxy#15]
I would like to be able to find Global Offset of a child of Widget nested down below in Widget.

So let's say I have following Widget tree:

W0
 |--W01
 |--W02
 |--W03
W1
 |--W11
 |--W12
 |--W13

I would like to layout W0 and W1, find Offset of W02 and W12 and inflate with widget which is positioned between W02 and W12.

What's the best way to do it?

I believe Boxy took me 1 step closer to achieving that but iterating over children to find their Offset seem problematic, approach I've taken is with 
```
RenderBox rb = element.findRenderObject() as RenderBox;
connectorOffset = rb.localToGlobal(Offset.zero);
```
...but I'm told I should not read Offset this way by framework.

**Comment by PixelToast** [comment]
Its not possible to read the offset of descendants because there is no way to guarantee that a child changing size will re-layout its grandparent.

Do you have a visual example of the layout you are trying to create?

**Comment by kobyhallx** [comment]
Would like to recreate Blender's Node Editor
![image](https://user-images.githubusercontent.com/102518238/161750595-eb1391f2-7e9a-44d4-95b3-f169bb6fd65b.png)

but with each Node starting as Scaffold.

**Comment by PixelToast** [comment]
Is the end goal to draw that line between them? You can do that entirely in a painter, it's generally safe to access RenderObjects during the paint phase and the framework shouldn't stop you.
