### ISSUE TITLE
How to remove a rendered widget? 

### ISSUE THREAD

**Issue by rupinderjeet** [PixelToast/flutter-boxy#16]
In `onLayout()`, I have some code like this:

    final source = getChild(#source);
    final sourceSize = source.layout(constraints);
    source.position(const Offset(-10000, 0));

I am using `sourceSize` to determine `source`'s size and apply this size to another widget. This is working for me. But, I want to remove `source` completely instead of hiding it at `(-10000, 0)`. How can I do this?

**Comment by PixelToast** [comment]
Call `source.ignore()`: https://pub.dev/documentation/boxy/latest/boxy/BaseBoxyChild/ignore.html

**Comment by rupinderjeet** [comment]
Thank you. This has helped me remove weird offset I was using. However, I have two more related questions.

1. Is the order of using `ignore` correct in below code?

```
final source = getChild(#source);
final sourceSize = source.layout(constraints);
source.position(Offset.zero);
source.ignore();
```

2. On a page, If a `Hero` widget, with tag `photo_hero`, is nested as a child of this dummy `source` widget, Boxy will layout it to get the size. But, this also means that I can no longer use the same `Hero` tag on that page again. Is this right? `Hero` widget tagged with `photo_hero` will be used with `source` widget and I will somehow need to tell actual widget and its `Hero` widget to use a different tag. Is this right?

**Comment by PixelToast** [comment]
Yes, that is correct, the child still exists in the Element tree preventing you from having an identical Hero. I'm not sure if the framework allows you to create and destroy a child in the same layout pass, that requires some more testing.

**Comment by rupinderjeet** [comment]
Thank you for your help and this project. There is a lot to learn for me in this codebase. You can close this issue, my query is answered.
