### ISSUE TITLE
Sliver in CustomBoxy

### ISSUE THREAD

**Issue by innocentalone** [PixelToast/flutter-boxy#2]
Hello, can we have a sliver inside a customboxy?
I am getting error.

Thanks in advance.

**Comment by PixelToast** [comment]
Unfortunately slivers are not supported as children of a CustomBoxy, maybe on the 2.0 release the API surface could be improved a bit here.

What use case do you have in mind specifically?

**Comment by innocentalone** [comment]
Actually, my client has got some Slivers (e.g., SliverList) and I have to do some 'fancy work' over it.

**Comment by RaviKavaiya** [comment]
@innocentalone Not sure, but for that we can use `SliverContainer` from this package.
@PixelToast thoughts?

**Comment by PixelToast** [comment]
A bunch of progress has been made in refactoring boxy to allow sliver delegates and children, stay tuned!

**Comment by PixelToast** [comment]
Sliver support was added in release 2.0.0
