### ISSUE TITLE
SliverContainer fill available space

### ISSUE THREAD

**Issue by RaviKavaiya** [PixelToast/flutter-boxy#3]
Hi once again...

I recently encountered the use of `SliverContainer` (very useful one!). Can we have option to provide BoxConstraints manually? Actually, I am wrapping a sliver inside it (which is scrollable) and it shrinks in a way that occupies only space taken by the sliver itself.

Is it possible that the `SliverContainer` fills the available space in parent (just like Expanded in Column) or option to provide manually?

I tried digging the source code. Unfortunately, I am new to such layout things and couldn't understand how these constraints work :grin:

Thanks.

**Comment by PixelToast** [comment]
The child of a SliverContainer is a sliver, which sizes itself on the main axis.

There is nothing I can really do here, maybe you wanted a SliverFillRemaining and NestedScrollView?

**Comment by RaviKavaiya** [comment]
Thanks for the help. I had no luck. But, the SliverContainer is not the problem. I think I need to explore a bit.

Thanks. ( You can close this issue )
