### ISSUE TITLE
Overriden shouldRelayout doesn't have access to BoxyDelegate

### ISSUE THREAD

**Issue by WasserEsser** [PixelToast/flutter-boxy#36]
I'm not sure if I'm being stupid, or if this is a bug or if the error message is wrong and this is not allowed (though it seems like it should?).

Consider this implementation of BoxyDelegate. The important part is the shouldRelayout function.

```dart
class TestBoxy extends BoxyDelegate {
  @override
  Size layout() {
    // do layout
  }

  @override
  bool shouldRelayout(covariant TestBoxy oldDelegate) {
    return children.length != oldDelegate.children.length;
  }
}
```

This will throw the following error on rebuild when the shouldRelayout function is trying to access either its own children or those of oldDelegate.

> The EvenlySizedBoxy boxy delegate attempted to get the context outside of its normal lifecycle.
You should only access the BoxyDelegate from its overridden methods.

Am I doing something wrong, is the error message wrong or is this a bug? I am accessing the properties of either delegate in an overridden method.

**Comment by pingbird** [comment]
if the children are updated in any way the boxy will be laid out automatically, the error you are getting is from accessing the old delegate's children from outside of its lifecycle

**Comment by pingbird** [comment]
Apologies if the docs are insufficient but the shouldRelayout and shouldRepaint methods are used in the same manner as [CustomPainer.shouldRepaint](https://api.flutter.dev/flutter/rendering/CustomPainter/shouldRepaint.html), to compare custom properties that you have added to the constructor of the delegate:

```dart
class _TreeViewBoxy extends BoxyDelegate {
  _TreeViewBoxy({
    required this.root,
    required this.verticalSpacing,
    required this.horizontalSpacing,
  });

  ...

  @override
  bool shouldRelayout(_TreeViewBoxy oldDelegate) =>
      root != oldDelegate.root ||
          verticalSpacing != oldDelegate.verticalSpacing ||
          horizontalSpacing != oldDelegate.horizontalSpacing;
}
```

If your delegate has no parameters then there is no reason to implement the method.
