### ISSUE TITLE
Example is slightly broken

### ISSUE THREAD

**Issue by 4amVim** [PixelToast/flutter-boxy#5]
The [example](https://github.com/PixelToast/flutter-boxy/tree/master/example) is broken.

[`blog_tile.dart`](https://github.com/PixelToast/flutter-boxy/blob/master/example/lib/pages/blog_tile.dart) tries to instantiate `AnimatedSize` but  without [the required `vsync` argument](https://api.flutter.dev/flutter/widgets/AnimatedSize/AnimatedSize.html).

**Comment by PixelToast** [comment]
The vsync argument was deprecated in https://github.com/flutter/flutter/pull/81067, waiting for it to hit stable
