### ISSUE TITLE
Use children's instrics when calculating intrinsics in CustomBoxy

### ISSUE THREAD

**Issue by soumya92** [PixelToast/flutter-boxy#7]
I'm probably not using this correctly, but I couldn't find a good example.

I want my CustomBoxy's intrinsic dimensions to be calculated based on the intrinsic dimensions of its children. In the simplest case, let's say something like:
```
class MyDelegate extends BoxyDelegate {
  // ...

  @override
  double minIntrinsicHeight(double width) =>
      children.map((e) => e.render.getMinIntrinsicHeight(width)).fold(0, max);
}
```

What I noticed is that when I do this, the intrinsic size changes as soon as I interact with the app. By adding some logging, it seems that `children` returns an empty array on the first pass (and `getChild(#id)` throws `The MyDelegate boxy delegate attempted to get a nonexistent child.`). But after any interaction, subsequent calls correctly return the list of children. Because of this, I cannot make the intrinsic size depend on children since on first calculation they are not available.

So my questions are:
- Is this supported at all? (e.g. is there a different way I should get children (or their intrinsic sizes) for this calculation?)
- If not, is that just something that's currently missing, or is it fundamentally difficult because of architectural reasons?

**Comment by PixelToast** [comment]
Looking into this

**Comment by PixelToast** [comment]
Fixed in 2.0.3, let me know if that worked for your use case!

**Comment by soumya92** [comment]
Works perfectly! Thanks for the incredibly quick fix!!

**Comment by MikeFP** [comment]
@PixelToast I don't know if it's related, but something similar happens on the first pass of `BoxyDelegate.layout()`. However, instead of empty children, it's a null `parentData`. The subsequent passes are ok and receive the proper data object.

**Comment by MikeFP** [comment]
@PixelToast Here it is: https://github.com/PixelToast/flutter-boxy/issues/9
